export enum NAMESROUTES {
  //ACCESS
  LOGIN = 'LOGIN',
  REGISTER = 'REGISTER',

  //APP
  APP_HOME = 'APP_HOME',

  //SECURITY
  APP_ROLE_LIST = 'APP_ROLE_LIST',
  APP_ROLE_WRITE = 'APP_ROLE_WRITE',
  APP_USER_LIST = 'APP_USER_LIST',
  APP_USER_WRITE = 'APP_USER_WRITE',
  APP_PERMISSION_LIST = 'APP_PERMISSION_LIST',

  //DEPARTMENT
  APP_DEPARTMENT_LIST = 'APP_DEPARTMENT_LIST',
  APP_DEPARTMENT_WRITE = 'APP_DEPARTMENT_WRITE',

  //EMPLOYEE
  APP_EMPLOYEE_LIST = 'APP_EMPLOYEE_LIST',
  APP_EMPLOYEE_WRITE = 'APP_EMPLOYEE_WRITE',

  //POSITION
  APP_POSITION_LIST = 'APP_POSITION_LIST',
  APP_POSITION_WRITE = 'APP_POSITION_WRITE',

  //RECORD
  APP_RECORD_LIST = 'APP_RECORD_LIST',
  APP_RECORD_WRITE = 'APP_RECORD_WRITE',

  //DOCUMENT
  APP_DOCUMENT_LIST = 'APP_DOCUMENT_LIST',
  APP_DOCUMENT_WRITE = 'APP_DOCUMENT_WRITE',
}

export type PermisionsRoutesApp = {
  routename: NAMESROUTES;
  dependencies: string[];
};
